Repository pw-software-engineering/2022_e-team, pull requests merged in 2022-05, with the labels that each got.

#45 Fixed routing in our api
  ECaterer.WebApi/Controllers/ClientController.cs
  ECaterer.WebApi/Controllers/MealsController.cs
  ECaterer.WebApi/Controllers/TestController.cs
Labels: bug

#47 producer orders views
  ECaterer.Web/ClientApp/src/app/app.module.ts
  ECaterer.Web/ClientApp/src/app/order/api/order.service.ts
  ECaterer.Web/ClientApp/src/app/order/api/orderDTO.ts
  ECaterer.Web/ClientApp/src/app/order/previewOrder/previewOrder.component.html
  ECaterer.Web/ClientApp/src/app/order/previewOrder/previewOrder.component.scss
  ECaterer.Web/ClientApp/src/app/order/previewOrder/previewOrder.component.spec.ts
  ECaterer.Web/ClientApp/src/app/order/previewOrder/previewOrder.component.ts
  ECaterer.Web/ClientApp/src/app/order/producer/producerOrders.component.html
  ECaterer.Web/ClientApp/src/app/order/producer/producerOrders.component.scss
  ECaterer.Web/ClientApp/src/app/order/producer/producerOrders.component.spec.ts
  ECaterer.Web/ClientApp/src/app/order/producer/producerOrders.component.ts
  ECaterer.Web/ClientApp/src/app/order/producerComplaint/producerComplaint.component.html
  ECaterer.Web/ClientApp/src/app/order/producerComplaint/producerComplaint.component.scss
  ECaterer.Web/ClientApp/src/app/order/producerComplaint/producerComplaint.component.spec.ts
  ECaterer.Web/ClientApp/src/app/order/producerComplaint/producerComplaint.component.ts
  ECaterer.Web/Controllers/OrderController.cs
  ECaterer.Web/DTO/OrderDTO/ComplaintDTO.cs
  ECaterer.Web/DTO/OrderDTO/PreviewOrderDTO.cs
  ECaterer.Web/DTO/OrderDTO/ProducerOrderDTO.cs
  ECaterer.Web/ECaterer.Web.csproj
Labels: ready to merge

#50 Improved QueryBuilder
  ECaterer.WebApi/Common/Builders/MealsQueryBuilder.cs
  ECaterer.WebApi/Common/Builders/OrdersQueryBuilder.cs
  ECaterer.WebApi/Common/Builders/QueryBuilder.cs
  ECaterer.WebApi/Common/Filters/Limit.cs
  ECaterer.WebApi/Common/Filters/Meals/MealCaloriesFilter.cs
  ECaterer.WebApi/Common/Filters/Meals/MealCaloriesHigherThanFilter.cs
  ECaterer.WebApi/Common/Filters/Meals/MealCaloriesLowerThanFilter.cs
  ECaterer.WebApi/Common/Filters/Meals/MealNameFilter.cs
  ECaterer.WebApi/Common/Filters/Meals/MealNameWithFilter.cs
  ECaterer.WebApi/Common/Filters/Meals/MealSort.cs
  ECaterer.WebApi/Common/Filters/Meals/MealVeganFilter.cs
  ECaterer.WebApi/Common/Filters/Offset.cs
  ECaterer.WebApi/Common/Filters/Orders/OrderEndDateFilter.cs
  ECaterer.WebApi/Common/Filters/Orders/OrderPriceFilter.cs
  ECaterer.WebApi/Common/Filters/Orders/OrderPriceHigherThanFilter.cs
  ECaterer.WebApi/Common/Filters/Orders/OrderPriceLowerThanFilter.cs
  ECaterer.WebApi/Common/Filters/Orders/OrderSort.cs
  ECaterer.WebApi/Common/Filters/Orders/OrderStartDateFilter.cs
  ECaterer.WebApi/Common/Filters/Orders/OrderStatusFilter.cs
  ECaterer.WebApi/Common/Interfaces/IFilter.cs
  ECaterer.WebApi/Services/MealRepository.cs
  ECaterer.WebApi/Services/OrderService.cs
Labels: help wanted
